name: Convert xv6-riscv-book to HTML

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-pdf:
    runs-on: ubuntu-24.04
    steps:

      - name: Install mpage
        run: |
          wget https://www.mesa.nl/pub/mpage/mpage-2.5.8.tgz
          tar -xvzf mpage-*.tgz
          make -C mpage-*/
          sudo make -C mpage-*/ install

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -qq update > /dev/null
          sudo apt-get -qq install ghostscript make latexmk dvisvgm preview-latex-style texlive-extra-utils zip latexml > /dev/null
          sudo apt-get -qq install texlive-latex-base > /dev/null
          sudo apt-get -qq install texlive-latex-extra > /dev/null

      - name: Build book
        run: make

      - name: Get latest bookml release
        run: |
          wget https://github.com/vlmantova/bookml/releases/latest/download/release.zip
          unzip release.zip

      - name: Build html
        run: |
          cp bookml/GNUmakefile .
          make -f GNUmakefile

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: auxdir/html/book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
